/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author macbook
 */
public class Absensi extends javax.swing.JFrame implements AbsensiInterface {

    @Override
    public void tambahData() {
        String nama = txtNama.getText();
        String nim = txtNim.getText();
        String status = cmbStatus.getSelectedItem().toString();

        if(nama.equals("Tulis Nama") || nama.isEmpty()) {
            JOptionPane.showMessageDialog(this,"Nama belum diisi");
            return;
        }

        if(nim.equals("Tulis NIM") || nim.isEmpty()) {
            JOptionPane.showMessageDialog(this,"NIM belum diisi");
            return;
        }

        if (cmbStatus.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(
                this,
                "Status absensi harus dipilih!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        DataStore.dataAbsensi.add(new Object[] {
            nama,
            nim,
            status
        });

        JOptionPane.showMessageDialog(
            this,
            "Data sudah ditambahkan",
            "Sukses",
            JOptionPane.INFORMATION_MESSAGE
        );

        resetForm();
    }

    @Override
    public void resetForm() {
        txtNama.setText("Tulis Nama");
        txtNama.setForeground(Color.GRAY);
        txtNim.setText("Tulis NIM");
        txtNim.setForeground(Color.GRAY);
        cmbStatus.setSelectedIndex(0);
    }

    /**
     * Creates new form Absensi
     */
    public Absensi() {
        initComponents();
        
        cmbStatus.removeAllItems();
        
        cmbStatus.addItem("--- Pilih ---");
        cmbStatus.addItem("Hadir");
        cmbStatus.addItem("Izin");
        cmbStatus.addItem("Alpha");
        
        txtNama.setText("Tulis Nama");
        txtNama.setForeground(Color.GRAY);
        
        txtNim.setText("Tulis NIM");
        txtNim.setForeground(Color.GRAY);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        bgJudul = new javax.swing.JPanel();
        cmbStatus = new javax.swing.JComboBox<>();
        txtNama = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnLihatData = new javax.swing.JButton();
        txtNim = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuExit = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuGit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(150, 170, 155));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJudul.setFont(new java.awt.Font("Serif", 1, 33)); // NOI18N
        lblJudul.setText("ABSENSI MAHASISWA");
        bg.add(lblJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 370, 80));

        bgJudul.setBackground(new java.awt.Color(200, 220, 210));
        bgJudul.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStatusActionPerformed(evt);
            }
        });
        bgJudul.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaKeyTyped(evt);
            }
        });
        bgJudul.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 160, -1));

        btnTambah.setText("Tambahkan");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        bgJudul.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 110, -1));

        btnLihatData.setText("Lihat Data");
        btnLihatData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatDataActionPerformed(evt);
            }
        });
        bgJudul.add(btnLihatData, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        txtNim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNimFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNimFocusLost(evt);
            }
        });
        txtNim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNimKeyTyped(evt);
            }
        });
        bgJudul.add(txtNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 160, -1));

        btnExit.setText("Keluar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        bgJudul.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        bg.add(bgJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 560, 350));

        menuExit.setText("File");

        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuExit.add(jMenuItem1);

        jMenuBar1.add(menuExit);

        jMenu2.setText("About");

        menuGit.setText("Github");
        menuGit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGitActionPerformed(evt);
            }
        });
        jMenu2.add(menuGit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        tambahData();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void cmbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStatusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbStatusActionPerformed

    private void btnLihatDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatDataActionPerformed
        // TODO add your handling code here:
        new DataAbsensi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLihatDataActionPerformed

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        // TODO add your handling code here:
        if (txtNama.getText().equals("Tulis Nama")) {
            txtNama.setText("");
            txtNama.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNamaFocusGained

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost
        // TODO add your handling code here:
        if (txtNama.getText().isEmpty()) {
            txtNama.setText("Tulis Nama");
            txtNama.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNamaFocusLost

    private void txtNimFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNimFocusGained
        // TODO add your handling code here:
        if (txtNim.getText().equals("Tulis NIM")) {
            txtNim.setText("");
            txtNim.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNimFocusGained

    private void txtNimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNimFocusLost
        // TODO add your handling code here:
        if (txtNim.getText().isEmpty()) {
            txtNim.setText("Tulis NIM");
            txtNim.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtNimFocusLost

    private void txtNamaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (!(Character.isLetter(c) || c == ' ' || c == '\'')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNamaKeyTyped

    private void txtNimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNimKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNimKeyTyped

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuGitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGitActionPerformed
        // TODO add your handling code here:
        try {
        java.awt.Desktop.getDesktop().browse(
                new java.net.URI("https://github.com/awalinashifa")
        );
        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
            this,
            "Gagal membuka link",
            "Peringatan",
            JOptionPane.ERROR_MESSAGE
            );
        } 
        
    }//GEN-LAST:event_menuGitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Absensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bgJudul;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLihatData;
    public javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JMenu menuExit;
    private javax.swing.JMenuItem menuGit;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNim;
    // End of variables declaration//GEN-END:variables
}
