/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas.pemrograman2;

import java.awt.Color;
import javax.swing.JOptionPane;
import java.util.List;

/**
 *
 * @author macbook
 */
public class produkGui extends javax.swing.JFrame {

    /**
     * Creates new form produkGui
     */
    // BARIS 1
    private List<Product> daftarProduk;
    private int selectedProdukId = 0; // <-- WAJIB ADA
    private int idProdukTerpilih = -1;

    public produkGui() {
        initComponents();
        loadHargaProduk();
        setLocationRelativeTo(null);
        setResizable(false);

        loadProdukDariDatabase();
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "No", "Produk", "Jumlah", "Total Harga", "Tanggal"
                }
        ));
    }

    private void loadProdukDariDatabase() {
        daftarProduk = TransaksiDAO.getAllProduk();
    }

    private void loadHargaProduk() {
        lblHarga1.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(1))
        );
        lblHarga2.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(2))
        );
        lblHarga3.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(3))
        );
        lblHarga4.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(4))
        );
        lblHarga5.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(5))
        );
        lblHarga6.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(6))
        );
        lblHarga7.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(7))
        );
        lblHarga8.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(8))
        );
        lblHarga9.setText(
                String.valueOf(TransaksiDAO.getHargaProdukById(9))
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblKembali = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnl1 = new javax.swing.JPanel();
        lblHarga1 = new javax.swing.JLabel();
        lblGambar1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblHarga2 = new javax.swing.JLabel();
        lblGambar2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblHarga3 = new javax.swing.JLabel();
        lblGambar3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblHarga4 = new javax.swing.JLabel();
        lblGambar4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblHarga5 = new javax.swing.JLabel();
        lblGambar5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblHarga6 = new javax.swing.JLabel();
        lblGambar6 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblHarga7 = new javax.swing.JLabel();
        lblGambar7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblHarga8 = new javax.swing.JLabel();
        lblGambar8 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblHarga9 = new javax.swing.JLabel();
        lblGambar9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtNamaProduk = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        simpan1 = new javax.swing.JButton();
        txtNamaProduk1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(184, 86, 57));

        jLabel8.setFont(new java.awt.Font("Apple Chancery", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Valerie Fashion ");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 10.png"))); // NOI18N
        jLabel12.setText("jLabel6");

        lblKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 13.png"))); // NOI18N
        lblKembali.setText("jLabel1");
        lblKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKembaliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKembaliMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 457, Short.MAX_VALUE)
                .addComponent(lblKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        jPanel3.setBackground(new java.awt.Color(250, 226, 188));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl1.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga1.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga1.setText("55.000");

        lblGambar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 1.png"))); // NOI18N
        lblGambar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblGambar1.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblHarga1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGambar1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga1)
                .addGap(63, 63, 63))
        );

        jPanel3.add(pnl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 6, 130, 170));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga2.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga2.setText("175.000");

        lblGambar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGambar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 2.png"))); // NOI18N
        lblGambar2.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblHarga2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGambar2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 6, 130, 170));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga3.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga3.setText("165.000");

        lblGambar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 3.png"))); // NOI18N
        lblGambar3.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGambar3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarga3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHarga3)
                .addGap(12, 12, 12))
        );

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 6, 130, 170));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga4.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga4.setText("95.000");

        lblGambar4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGambar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 4 .png"))); // NOI18N
        lblGambar4.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHarga4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGambar4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 188, 132, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga5.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga5.setText("85.000");

        lblGambar5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGambar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 5.png"))); // NOI18N
        lblGambar5.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblHarga5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 188, 126, -1));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga6.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga6.setText("135.000");

        lblGambar6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGambar6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 6.png"))); // NOI18N
        lblGambar6.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(lblHarga6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGambar6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGambar6, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga6)
                .addGap(12, 12, 12))
        );

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 188, 130, 172));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga7.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga7.setText("125.000");

        lblGambar7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGambar7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 7.png"))); // NOI18N
        lblGambar7.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHarga7, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGambar7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar7, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 366, 140, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga8.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga8.setText("100.000");

        lblGambar8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGambar8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 8.png"))); // NOI18N
        lblGambar8.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHarga8, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGambar8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar8, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 366, 130, -1));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        lblHarga9.setFont(new java.awt.Font("PingFang HK", 1, 15)); // NOI18N
        lblHarga9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarga9.setText("55.000");

        lblGambar9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGambar9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 9.png"))); // NOI18N
        lblGambar9.setPreferredSize(new java.awt.Dimension(120, 120));
        lblGambar9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGambar9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblHarga9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGambar9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHarga9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 366, 130, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 550));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaProdukActionPerformed(evt);
            }
        });
        jPanel4.add(txtNamaProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 280, -1));

        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });
        jPanel4.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 280, -1));

        jLabel3.setText("Masukan NAMA");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        simpan.setText("TAMPILKAN TRANSAKSI (ADMIN)");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel4.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 420, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Produk", "Total Harga"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 420, 290));

        jLabel5.setText("Jumlah Pembelian");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("0");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));

        jLabel4.setText("HARGA PRODUK");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        simpan1.setText("BUY Sekarang");
        simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan1ActionPerformed(evt);
            }
        });
        jPanel4.add(simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 420, 30));
        jPanel4.add(txtNamaProduk1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 280, -1));

        jLabel6.setText("Nama Produk");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TABEL PEMBELIAN");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel9.setText(":");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 20, -1));

        jLabel10.setText(":");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 20, -1));

        jLabel11.setText(":");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 20, -1));

        jLabel13.setText(":");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 20, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 440, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblGambar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar1MouseClicked
        selectedProdukId = 1;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 1)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar1MouseClicked

    private void lblGambar6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar6MouseClicked
        selectedProdukId = 6;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 6)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar6MouseClicked

    private void lblGambar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar2MouseClicked
        selectedProdukId = 2;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 2)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar2MouseClicked

    private void lblGambar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar3MouseClicked
        selectedProdukId = 3;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 3)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar3MouseClicked

    private void lblGambar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar4MouseClicked
        selectedProdukId = 4;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 4)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar4MouseClicked

    private void lblGambar5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar5MouseClicked
        selectedProdukId = 5;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 5)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar5MouseClicked

    private void lblGambar7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar7MouseClicked
        selectedProdukId = 7;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 7)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar7MouseClicked

    private void lblGambar8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar8MouseClicked
        selectedProdukId = 8;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 8)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar8MouseClicked

    private void lblGambar9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGambar9MouseClicked
        selectedProdukId = 9;
        Product p = daftarProduk.stream()
                .filter(x -> x.getId() == 9)
                .findFirst()
                .orElse(null);

        if (p != null) {
            txtNamaProduk1.setText(p.getNama());
            jLabel2.setText(String.valueOf(p.getHarga()));
            idProdukTerpilih = p.getId();
        }
    }//GEN-LAST:event_lblGambar9MouseClicked

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void lblKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKembaliMouseClicked
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblKembaliMouseClicked

    private void lblKembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKembaliMouseEntered
        lblKembali.setForeground(Color.RED);
    }//GEN-LAST:event_lblKembaliMouseEntered

    private void lblKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKembaliMouseExited
        lblKembali.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblKembaliMouseExited

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        TransaksiProduk dasb = new TransaksiProduk();
        dasb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_simpanActionPerformed

    private void simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan1ActionPerformed
        // TODO add your handling code here:

        if (txtNamaProduk.getText().trim().isEmpty()
                || txtNamaProduk1.getText().trim().isEmpty()
                || txtJumlah.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "From Pemesanan Wajib di isi",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE
            );
            return; // HENTIKAN proses BUY
        }

        String pembeli = txtNamaProduk.getText();
        int idProduk = selectedProdukId; // dari klik gambar
        int jumlah = Integer.parseInt(txtJumlah.getText());
        int harga = Integer.parseInt(jLabel2.getText());
        int total = harga * jumlah;

        TransaksiDAO.insertTransaksi(
                pembeli,
                idProduk,
                jumlah,
                total
        );

        TransaksiDAO.loadHistorisPembelian(
                jTable1,
                pembeli
        );

        JOptionPane.showMessageDialog(this, "Transaksi berhasil!");
    }//GEN-LAST:event_simpan1ActionPerformed

    private void txtNamaProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaProdukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaProdukActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(produkGui.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(produkGui.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(produkGui.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(produkGui.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new produkGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGambar1;
    private javax.swing.JLabel lblGambar2;
    private javax.swing.JLabel lblGambar3;
    private javax.swing.JLabel lblGambar4;
    private javax.swing.JLabel lblGambar5;
    private javax.swing.JLabel lblGambar6;
    private javax.swing.JLabel lblGambar7;
    private javax.swing.JLabel lblGambar8;
    private javax.swing.JLabel lblGambar9;
    private javax.swing.JLabel lblHarga1;
    private javax.swing.JLabel lblHarga2;
    private javax.swing.JLabel lblHarga3;
    private javax.swing.JLabel lblHarga4;
    private javax.swing.JLabel lblHarga5;
    private javax.swing.JLabel lblHarga6;
    private javax.swing.JLabel lblHarga7;
    private javax.swing.JLabel lblHarga8;
    private javax.swing.JLabel lblHarga9;
    private javax.swing.JLabel lblKembali;
    private javax.swing.JPanel pnl1;
    private javax.swing.JButton simpan;
    private javax.swing.JButton simpan1;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNamaProduk;
    private javax.swing.JTextField txtNamaProduk1;
    // End of variables declaration//GEN-END:variables

}
