/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas.pemrograman2;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author macbook
 */
public class TransaksiProduk extends javax.swing.JFrame {

    /**
     * Creates new form produk
     */
    public TransaksiProduk() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Nama Pembeli",
                    "Nama Produk",
                    "Jumlah Produk Dibeli",
                    "Tanggal Transaksi",
                    "Kode Transaksi (KEY)"
                }
        ));

        TransaksiDAO.loadTransaksiAdmin(tabelTransaksi);
        tampilDataProduk();
    }

    private void tampilDataProduk() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Produk");
        model.addColumn("Nama Produk");
        model.addColumn("Harga");

        try {
            String sql = "SELECT * FROM produk";
            java.sql.Connection conn = koneksi.getConnection(); // sesuaikan
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet rs = stm.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_produk"),
                    rs.getString("nama_produk"),
                    rs.getInt("harga")
                });
            }

            TabelProdukGudang.setModel(model);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblKembali = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTransaksi = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        namaTransaksiE = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CodeTrans = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        namaProdukE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hargaProdukE = new javax.swing.JTextField();
        updateToko = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelProdukGudang = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        idProduk = new javax.swing.JTextField();
        deleteTrans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(184, 86, 57));

        jLabel8.setFont(new java.awt.Font("Apple Chancery", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TRANSAKSI (ADMIN)");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 10.png"))); // NOI18N
        jLabel12.setText("jLabel6");

        lblKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uas/pemrograman2/GAMBAR 13.png"))); // NOI18N
        lblKembali.setText("jLabel1");
        lblKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKembaliMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblKembaliMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblKembaliMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(lblKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        update.setText("UPDATE NAMA PEMBELI");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel4.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 430, 30));

        tabelTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Pembeli", "Nama Produk", "Jumlah Produk Di beli", "Tanggal Transaksi", "Kode Transaksi (KEY)"
            }
        ));
        tabelTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelTransaksi);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 850, 210));

        jLabel1.setText("Rubah Nama Pembeli");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel4.add(namaTransaksiE, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 600, -1));

        jLabel4.setText("Masukan Kode Transaksi");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));
        jPanel4.add(CodeTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 600, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("EDIT TOKO GUDANG"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Rubah Nama Produk");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, 20));
        jPanel3.add(namaProdukE, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 200, 30));

        jLabel5.setText("Rubah Harga Produk");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, 20));
        jPanel3.add(hargaProdukE, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 200, 30));

        updateToko.setText("UPDATE PRODUK GUDANG");
        updateToko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateTokoActionPerformed(evt);
            }
        });
        jPanel3.add(updateToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 330, 30));

        TabelProdukGudang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Produk", "Harga Produk"
            }
        ));
        TabelProdukGudang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelProdukGudangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TabelProdukGudang);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 490, 160));

        jLabel6.setText("ID Produk");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, -1, 30));
        jPanel3.add(idProduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 200, 30));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 850, 190));

        deleteTrans.setText("HAPUS TRANSAKSI");
        deleteTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTransActionPerformed(evt);
            }
        });
        jPanel4.add(deleteTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 410, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 890, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKembaliMouseClicked
        new home().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblKembaliMouseClicked

    private void lblKembaliMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKembaliMouseEntered
        lblKembali.setForeground(Color.RED);
    }//GEN-LAST:event_lblKembaliMouseEntered

    private void lblKembaliMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKembaliMouseExited
        lblKembali.setForeground(Color.BLUE);
    }//GEN-LAST:event_lblKembaliMouseExited

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if (CodeTrans.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Kode transaksi harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            int kode = Integer.parseInt(CodeTrans.getText());
            String namaE = namaTransaksiE.getText();

            TransaksiDAO.updateNamaPembeli(kode, namaE);
            TransaksiDAO.loadTransaksiAdmin(tabelTransaksi);

            CodeTrans.setText("");
            namaTransaksiE.setText("");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Kode transaksi harus berupa angka!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_updateActionPerformed

    private void updateTokoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateTokoActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        if (namaProdukE.getText().trim().isEmpty()
                || hargaProdukE.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Data tidak boleh kosong!");
            return;
        }

        try {
            int idPro = Integer.parseInt(idProduk.getText());
            String namaProduk = namaProdukE.getText();
            int harga = Integer.parseInt(hargaProdukE.getText());

            TransaksiDAO.updateProdukById(idPro, namaProduk, harga);
            tampilDataProduk(); // refresh JTable

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!");
        }

    }//GEN-LAST:event_updateTokoActionPerformed

    private void deleteTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTransActionPerformed
        // TODO add your handling code here:

        if (CodeTrans.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Kode transaksi harus diisi!",
                    "Peringatan",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            int kode = Integer.parseInt(CodeTrans.getText());

            int konfirmasi = JOptionPane.showConfirmDialog(
                    this,
                    "Yakin ingin menghapus transaksi ini?",
                    "Konfirmasi",
                    JOptionPane.YES_NO_OPTION
            );

            if (konfirmasi == JOptionPane.YES_OPTION) {
                TransaksiDAO.deleteTransaksi(kode);
                TransaksiDAO.loadTransaksiAdmin(tabelTransaksi);

                // Clear field setelah hapus
                CodeTrans.setText("");
                namaTransaksiE.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Kode transaksi harus berupa angka!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }

    }//GEN-LAST:event_deleteTransActionPerformed

    private void TabelProdukGudangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelProdukGudangMouseClicked
        // TODO add your handling code here:
        int row = TabelProdukGudang.getSelectedRow();
        if (row == -1) {
            return;
        }

        // Ambil data dari JTable
        String id = TabelProdukGudang.getValueAt(row, 0).toString();
        String namaProduk = TabelProdukGudang.getValueAt(row, 1).toString();
        String harga = TabelProdukGudang.getValueAt(row, 2).toString();

        // Set ke JTextField
        idProduk.setText(id);          // jika ada
        namaProdukE.setText(namaProduk);      // Rubah Nama Produk
        hargaProdukE.setText(harga);          // Rubah Harga Produk
    }//GEN-LAST:event_TabelProdukGudangMouseClicked

    private void tabelTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelTransaksiMouseClicked
        // TODO add your handling code here:
        int row = tabelTransaksi.getSelectedRow();
        if (row == -1) {
            return;
        }

        // Ambil data dari JTable
        String kodeTransaksi = tabelTransaksi.getValueAt(row, 4).toString();
        String namaPembeli = tabelTransaksi.getValueAt(row, 0).toString();

        // Isi ke JTextField
        CodeTrans.setText(kodeTransaksi);
        namaTransaksiE.setText(namaPembeli);
    }//GEN-LAST:event_tabelTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiProduk.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiProduk.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiProduk.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiProduk.class.getName())
                    .log(java.util.logging.Level.SEVERE, null, ex);
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CodeTrans;
    private javax.swing.JTable TabelProdukGudang;
    private javax.swing.JButton deleteTrans;
    private javax.swing.JTextField hargaProdukE;
    private javax.swing.JTextField idProduk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblKembali;
    private javax.swing.JTextField namaProdukE;
    private javax.swing.JTextField namaTransaksiE;
    private javax.swing.JTable tabelTransaksi;
    private javax.swing.JButton update;
    private javax.swing.JButton updateToko;
    // End of variables declaration//GEN-END:variables

}
